import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Pageanimations from "./components/Pageanimations";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Convex Energy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <Pageanimations></Pageanimations>

      <Navbar />
        {children}
      <Footer />
      </body>
    </html>
  );
}
